name: LAN of DOOM
bio: 'est. 2005'
picture: 'assets/images/profile.jpg'

url: https://lanofdoom.com
permalink: /:title/

facebook: https://www.facebook.com/groups/188930077975373/
steam: https://steamcommunity.com/groups/wanofdoom/